version: '3.7'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: hrmdb
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   container_name: "marnix_postgres"
  #   networks:
  #     - marnix
  #   # logging:
  #   #   driver: "json-file"
  #   #   options:
  #   #     max-size: "50M"
  #   #     max-file: "5"

  marnix:
    build: .
    init: true
    restart: always
    volumes:
      - .:/opt/app/src
    command: sh -c "./deployment/deploy.sh"
    ports:
      - 8090:8090
    container_name: "boiler_plate"
    networks:
      - boiler
    # depends_on: [db]

networks:
  boiler:
    driver: "bridge"
    name: "boiler"
